server:
  port: ${PORT:8080}
  max-http-request-header-size: 64KB

spring:
  application:
    name: shelfscanai

  config:
    import: optional:azure-keyvault://

  cloud:
    azure:
      keyvault:
        secret:
          property-sources:
            - name: shelfscan-kv
              endpoint: https://shelfscan-kv-dev.vault.azure.net/
              secret-keys:
                - spring-datasource-url
                - spring-datasource-username
                - spring-datasource-password
                - app-blob-connection-string
                - app-blob-container

  datasource:
    url: ${spring-datasource-url}
    username: ${spring-datasource-username}
    password: ${spring-datasource-password}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: dbo
    show-sql: true

app:
  blob:
    connection-string: ${app-blob-connection-string}
    container: ${app-blob-container}

logging:
  level:
    com.azure: DEBUG
    com.azure.spring: DEBUG
    org.springframework.boot.context.config: DEBUG